API/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from API import views

router = DefaultRouter()
router.register('productos',viewset=views.ProdctoViewSet, basename='producto')
router.register('contactos',viewset=views.ContactoViewSet, basename='contacto')
router.register('marcas',viewset=views.MarcaViewSet, basename='marca')

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth', include('rest_framework.urls', namespace='rest_framework'))
]

tienda/urls.py
from django.urls import path , include
from tienda import views
from tienda.views import ProfileUpdate

urlpatterns = [
    path("", views.home, name='home'),
    path("contacto/", views.contacto, name='contacto'),
    path("galeria/", views.galeria, name='galeria'),
    path("sobremi/", views.sobremi, name='sobremi'),
    path("agregar-producto/", views.agregar_producto, name='agregar_producto'),
    path("agregar-marca/", views.agregar_marca, name='agregar_marca'),
    path("listar-contactos/", views.listar_contactos, name='listar_contactos'),
    path("listar-productos/", views.listar_productos, name='listar_productos'),
    path("modificar-productos/<id>/", views.modificar_producto, name='modificar_productos'),
    path("eliminar-producto/<id>/", views.eliminar_producto, name='eliminar_producto'),
    path("detalle-producto/<id>/", views.detalle_producto, name='detalle_producto'),
    path("listar-marcas/", views.listar_marcas, name='listar_marcas'),
    path("modificar-marca/<id>/", views.modificar_marca, name='modificar_marca'),
    path("eliminar-marca/<id>/", views.eliminar_marca, name='eliminar_marca'),
    path("registro/", views.registro, name="registro"),
    path("carrito/", include('carrito.urls')),
    path("accounts/profile/", ProfileUpdate.as_view(), name='profile'),
]

tiendateck/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('api/', include('API.urls')),
    path("admin/", admin.site.urls),
    path("", include('tienda.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/models.py
from django.db import models

# Create your models here.

class Marca(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre
    
    
class Prodcto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    nuevo = models.BooleanField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    fecha_fabricacion = models.DateField()
    imagen = models.ImageField(upload_to="productos", null=True)

    def __str__(self):
        return self.nombre

opciones_consultas = [
    [0, "consulta"],
    [1, "reclamo"],
    [2, "sugerencia"],
    [3, "felicitaciones"]
]
    
class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensaje = models.TextField()
    avisos = models.BooleanField()
    
    def __str__(self):
        cadena= self.nombre+","+self.tipo_consulta
        return cadena

from django.contrib.auth.models import User
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="profiles", null=True , blank=True)
    bio = models.TextField(null=True , blank=True)
    link = models.URLField(max_length=200, null=True , blank=True)

tienda/forms.py
from django import forms
from .models import Contacto , Prodcto , Marca , Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .validators import MaxSizeFileValidaor
from django.forms import ValidationError


class ContactoForm(forms.ModelForm):
    
    class Meta:
        model = Contacto
        #fields = ["nombre" , "correo" , "ripo_consulta" , "mensaje" , "avisos"]
        fields = '__all__'
        
        
class ProductoForm(forms.ModelForm):
    
    nombre = forms.CharField(max_length=50, min_length=3)
    precio = forms.IntegerField(max_value=1000000,min_value=1)
    imagen = forms.ImageField(validators=[MaxSizeFileValidaor(max_file_size=2)])
    
    def clean_nombre(self):
        nombre = self.cleaned_data["nombre"]    
        existe = Prodcto.objects.filter(nombre__iexact=nombre).exists()
        
        if existe:
            raise ValidationError("Este nombre ya existe.")
        
        return nombre
    
    class Meta:
        model = Prodcto
        fields = '__all__'
        
        widgets = {
            "fecha_fabricacion": forms.SelectDateWidget()
        }
        
class MarcaForm(forms.ModelForm):
    
    def clean_nombre(self):
        nombre = self.cleaned_data["nombre"]    
        existe = Marca.objects.filter(nombre__iexact=nombre).exists()
        
        if existe:
            raise ValidationError("Esta marca ya existe.")

        return nombre
    class Meta:
        model = Marca
        fields = '__all__'
        
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username","first_name","last_name","email","password1","password2"]
        exclude = ()
        # Saca los mensajes de ayuda
        help_texts = {
            'username': None,
            'first_name': None,
            'last_name': None,
            'email': None,
            'password1' : None,
            'password2' : None
        }
        
class ProfileForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ['avatar','bio','link']
        widgets = {
            'avatar' : forms.ClearableFileInput(attrs={'class':'form-control-file mt-3'}),
            'bio' : forms.Textarea(attrs={'class':'form-control mt-3','rows':3, 'placeholder':'Biografía'}),
            'link': forms.URLInput(attrs={'class':'form-control mt-3','placeholder':'Enlace'}),
        }

tienda/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.urls import reverse_lazy
from .models import Prodcto , Marca ,Contacto ,Profile
from .forms import ContactoForm , ProductoForm ,MarcaForm , CustomUserCreationForm , ProfileForm , User
from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import Http404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required , permission_required

# Create your views here.
""""
Vistas Home con buscador
"""
def home(request):
    if(request.GET.get('buscar')):
        data = Prodcto.objects.filter(
            Q(nombre__icontains = request.GET.get('buscar')) |
            Q(descripcion__icontains = request.GET.get('buscar'))|
            Q(marca__nombre__icontains = request.GET.get('buscar'))
            ).distinct()
    else:
        data = Prodcto.objects.all()
    return render(request, 'tienda/home.html', {'data': data})

""""
Vistas Contacto

"""
def contacto(request):
    data = {
        'form' : ContactoForm()
    }
    
    if request.method == 'POST':
        formulario = ContactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, 'Mensaje Guardado Correctamente')
        else:
            data['form'] = formulario
        
    return render(request, 'tienda/contacto.html' , data)

@permission_required('tienda.view_contacto')
def listar_contactos(request):
    mensajes = Contacto.objects.all()
    page = request.GET.get('page',1)
    
    try:
        paginator = Paginator(mensajes, 4)
        mensajes = paginator.page(page)
    except:
        raise Http404
    
    
    data = {
        'mensajes' : mensajes,
        'paginator' : paginator
    }
    
    return render(request, 'contacto/listar.html', data)

""""
Galeria

"""

def galeria(request):
    return render(request, 'tienda/galeria.html')

""""
Registro

"""

def registro(request):
    data = {
        'form' : CustomUserCreationForm
    }
    
    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data['username'], password=formulario.cleaned_data['password1'])
            login(request, user)
            messages.success(request, 'Te has Registrado Correctamente')
            #redirigir al home
            return redirect(to='home')
        data['form'] = formulario
            
    return render(request, 'registration/registro.html', data)


""""
Vistas Productos

"""
@permission_required('tienda.add_prodcto')
def agregar_producto(request):
    data = {
        'form' : ProductoForm()
    }
    
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Producto Agregado Correcatmente")
        else:
            data['form'] = formulario
    return render(request, 'producto/agregar.html', data)

@permission_required('tienda.view_prodcto')
def listar_productos(request):
    productos = Prodcto.objects.all()
    page = request.GET.get('page',1)
    
    try:
        paginator = Paginator(productos, 4)
        productos = paginator.page(page)
    except:
        raise Http404
    
    
    data = {
        'productos' : productos,
        'paginator' : paginator
    }
    
    return render(request, 'producto/listar.html', data)

@permission_required('tienda.change_prodcto')
def modificar_producto(request, id):
    
    producto = get_object_or_404(Prodcto, id=id)
    
    data = {
        'form': ProductoForm(instance=producto)
    }
    
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Editado Correcatmente")
            return redirect(to="listar_productos")
        data["form"] = formulario
        
    return render(request, 'producto/modificar.html', data)

@permission_required('tienda.delete_prodcto')
def eliminar_producto(request, id):
    producto = get_object_or_404(Prodcto, id=id)
    producto.delete()
    messages.success(request, "Eliminado Correcatmente")
    return redirect(to="listar_productos")

def detalle_producto(request, id):
    producto = get_object_or_404(Prodcto, id=id)
    #print(producto.precio)
    return render(request, 'producto/detalle.html', {'producto': producto})

""""
Vistas Marcas

"""
@permission_required('tienda.add_marca')
def agregar_marca(request):
    data = {
        'form' : MarcaForm()
    }
    
    if request.method == 'POST':
        formulario = MarcaForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Marca Agregada Correcatmente")
        else:
            data['form'] = formulario
    return render(request, 'marca/agregar.html', data)

@permission_required('tienda.view_marca')
def listar_marcas(request):
    marcas = Marca.objects.all()
    page = request.GET.get('page',1)
    
    try:
        paginator = Paginator(marcas, 4)
        marcas = paginator.page(page)
    except:
        raise Http404
    
    
    data = {
        'marcas' : marcas,
        'paginator' : paginator
    }
    
    return render(request, 'marca/listar.html', data)

@permission_required('tienda.change_prodcto')
def modificar_marca(request, id):
    
    marca = get_object_or_404(Marca, id=id)
    
    data = {
        'form': MarcaForm(instance=marca)
    }
    
    if request.method == 'POST':
        formulario = MarcaForm(data=request.POST, instance=marca)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Editado Correcatmente")
            return redirect(to="listar_marcas")
        data["form"] = formulario
        
    return render(request, 'marca/modificar.html', data)

@permission_required('tienda.delete_prodcto')
def eliminar_marca(request, id):
    marca = get_object_or_404(Marca, id=id)
    marca.delete()
    messages.success(request, "Eliminado Correcatmente")
    return redirect(to="listar_marcas")


""""
Vistas Perfil

"""

from django.views.generic.edit import UpdateView
from django.utils.decorators import method_decorator

@method_decorator(login_required, name='dispatch')
class ProfileUpdate(UpdateView):
    form_class = ProfileForm
    success_url = reverse_lazy('profile')
    
    def get_object(self):
        try:
            return Profile.objects.get(user=self.request.user)
        except Profile.DoesNotExist:
            return Profile.objects.create(user=self.request.user)
    
    
""""
Vistas Sobre mi

"""

def sobremi(request):
    return render(request, 'tienda/sobremi.html')

tienda/templates/marca/agregar.html
{% extends 'tienda/base.html' %}


{% block contenido %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card mt-4 mb-4">
            <div class="card-body">
                <h2>Agregar Marca</h2>
                <hr>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form | crispy}}

                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <input type="submit" value="Guardar" class="btn btn-primary">
                    </div>
                    {{mensaje}}
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

tienda/templates/marca/listar.html
{% extends 'tienda/base.html' %}


{% block js %}
    <script>
        function eliminarMarca(id){
            Swal.fire({
                "title": "¿Estas seguro?",
                "text" : "No podras deshacer",
                "icon" : "question",
                "showCancelButton": true,
                "cancelButtonText": "Cancelar",
                "confirmButtonText": "Si, Eliminar",
                "reverseButtons":true,
                "confirmButtonColor" : "#dc3545"
            })
            .then(function(result){
                if(result.isConfirmed){
                    window.location.href = "/eliminar-marca/" + id + "/"
                }
            })
        }
    </script>
{% endblock %}
    

{% block contenido %}

{% load humanize %}
<div class="card mt-4">
    <div class="card-body">
        <h2 class="mb-3">Listado de Marcas</h2>
        <hr>
        <table class="text-center table table-striped table-hover table-responsive-sm">
            <tr>
                <th>Nombre</th>
                <th>Opciones</th>
            </tr>
        
        
            {% for m in marcas %}
            <tr>
                <td>{{ m.nombre | title }}</td>
                <td>
                    {% if perms.tienda.change_marca %}
                    <a class="btn btn-info btn-sm" href="{% url 'modificar_marca' m.id %}">Editar</a>
                    {% endif %}
                    {% if perms.tienda.delete_marca %}
                    <a class="btn btn-danger btn-sm" href="#" onclick="eliminarMarca({{m.id}})">Eliminar</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        <hr>
        <div>
            {% include 'marca/paginator.html' %}
        </div>
    </div>
</div>

<div class="irinicio">
    <button  type="reset" value="Inicio" class="btn btn-secondary">
        <a class="botonCancelar" href="{% url 'home' %}">
            Inicio
        </a>
    </button>
</div>

{% endblock %}

tienda/templates/marca/modificar.html
{% extends 'tienda/base.html' %}


{% block contenido %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card mt-4 mb-4">
            <div class="card-body">
                <h2>Editar Marcas</h2>
                <hr>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form | crispy}}

                    <div class="d-flex justify-content-end">

                        <button  type="reset" value="Cancelar" class="btn btn-secondary">
                            <a class="botonCancelar" href="{% url 'listar_marcas' %}">
                                Cancelar
                            </a></button>
                        &nbsp;
                        <input type="submit" value="Editar" class="btn btn-primary">
                    </div>
                    {{mensaje}}
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

tienda/templates/marca/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if marcas.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ marcas.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != marcas.number and paginator.num_pages > 7 %} 
                {% if marcas.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ marcas.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == marcas.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == marcas.number %}
            <li class="page-item {% if page == marcas.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if marcas.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ marcas.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if marcas.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ marcas.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if marcas.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ marcas.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}