API/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from API import views

router = DefaultRouter()
router.register('productos',viewset=views.ProdctoViewSet, basename='producto')
router.register('contactos',viewset=views.ContactoViewSet, basename='contacto')
router.register('marcas',viewset=views.MarcaViewSet, basename='marca')

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth', include('rest_framework.urls', namespace='rest_framework'))
]

tienda/urls.py
from django.urls import path , include
from tienda import views
from tienda.views import ProfileUpdate

urlpatterns = [
    path("", views.home, name='home'),
    path("contacto/", views.contacto, name='contacto'),
    path("galeria/", views.galeria, name='galeria'),
    path("sobremi/", views.sobremi, name='sobremi'),
    path("agregar-producto/", views.agregar_producto, name='agregar_producto'),
    path("agregar-marca/", views.agregar_marca, name='agregar_marca'),
    path("listar-contactos/", views.listar_contactos, name='listar_contactos'),
    path("listar-productos/", views.listar_productos, name='listar_productos'),
    path("modificar-productos/<id>/", views.modificar_producto, name='modificar_productos'),
    path("eliminar-producto/<id>/", views.eliminar_producto, name='eliminar_producto'),
    path("detalle-producto/<id>/", views.detalle_producto, name='detalle_producto'),
    path("listar-marcas/", views.listar_marcas, name='listar_marcas'),
    path("modificar-marca/<id>/", views.modificar_marca, name='modificar_marca'),
    path("eliminar-marca/<id>/", views.eliminar_marca, name='eliminar_marca'),
    path("registro/", views.registro, name="registro"),
    path("carrito/", include('carrito.urls')),
    path("accounts/profile/", ProfileUpdate.as_view(), name='profile'),
]

tiendateck/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('api/', include('API.urls')),
    path("admin/", admin.site.urls),
    path("", include('tienda.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/models.py
from django.db import models

# Create your models here.

class Marca(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre
    
    
class Prodcto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    nuevo = models.BooleanField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    fecha_fabricacion = models.DateField()
    imagen = models.ImageField(upload_to="productos", null=True)

    def __str__(self):
        return self.nombre

opciones_consultas = [
    [0, "consulta"],
    [1, "reclamo"],
    [2, "sugerencia"],
    [3, "felicitaciones"]
]
    
class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensaje = models.TextField()
    avisos = models.BooleanField()
    
    def __str__(self):
        cadena= self.nombre+","+self.tipo_consulta
        return cadena

from django.contrib.auth.models import User
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="profiles", null=True , blank=True)
    bio = models.TextField(null=True , blank=True)
    link = models.URLField(max_length=200, null=True , blank=True)

tienda/forms.py
from django import forms
from .models import Contacto , Prodcto , Marca , Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .validators import MaxSizeFileValidaor
from django.forms import ValidationError


class ContactoForm(forms.ModelForm):
    
    class Meta:
        model = Contacto
        #fields = ["nombre" , "correo" , "ripo_consulta" , "mensaje" , "avisos"]
        fields = '__all__'
        
        
class ProductoForm(forms.ModelForm):
    
    nombre = forms.CharField(max_length=50, min_length=3)
    precio = forms.IntegerField(max_value=1000000,min_value=1)
    imagen = forms.ImageField(validators=[MaxSizeFileValidaor(max_file_size=2)])
    
    def clean_nombre(self):
        nombre = self.cleaned_data["nombre"]    
        existe = Prodcto.objects.filter(nombre__iexact=nombre).exists()
        
        if existe:
            raise ValidationError("Este nombre ya existe.")
        
        return nombre
    
    class Meta:
        model = Prodcto
        fields = '__all__'
        
        widgets = {
            "fecha_fabricacion": forms.SelectDateWidget()
        }
        
class MarcaForm(forms.ModelForm):
    
    def clean_nombre(self):
        nombre = self.cleaned_data["nombre"]    
        existe = Marca.objects.filter(nombre__iexact=nombre).exists()
        
        if existe:
            raise ValidationError("Esta marca ya existe.")

        return nombre
    class Meta:
        model = Marca
        fields = '__all__'
        
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username","first_name","last_name","email","password1","password2"]
        exclude = ()
        # Saca los mensajes de ayuda
        help_texts = {
            'username': None,
            'first_name': None,
            'last_name': None,
            'email': None,
            'password1' : None,
            'password2' : None
        }
        
class ProfileForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ['avatar','bio','link']
        widgets = {
            'avatar' : forms.ClearableFileInput(attrs={'class':'form-control-file mt-3'}),
            'bio' : forms.Textarea(attrs={'class':'form-control mt-3','rows':3, 'placeholder':'Biografía'}),
            'link': forms.URLInput(attrs={'class':'form-control mt-3','placeholder':'Enlace'}),
        }

tienda/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.urls import reverse_lazy
from .models import Prodcto , Marca ,Contacto ,Profile
from .forms import ContactoForm , ProductoForm ,MarcaForm , CustomUserCreationForm , ProfileForm , User
from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import Http404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required , permission_required

# Create your views here.
""""
Vistas Home con buscador
"""
def home(request):
    if(request.GET.get('buscar')):
        data = Prodcto.objects.filter(
            Q(nombre__icontains = request.GET.get('buscar')) |
            Q(descripcion__icontains = request.GET.get('buscar'))|
            Q(marca__nombre__icontains = request.GET.get('buscar'))
            ).distinct()
    else:
        data = Prodcto.objects.all()
    return render(request, 'tienda/home.html', {'data': data})

""""
Vistas Contacto

"""
def contacto(request):
    data = {
        'form' : ContactoForm()
    }
    
    if request.method == 'POST':
        formulario = ContactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, 'Mensaje Guardado Correctamente')
        else:
            data['form'] = formulario
        
    return render(request, 'tienda/contacto.html' , data)

@permission_required('tienda.view_contacto')
def listar_contactos(request):
    mensajes = Contacto.objects.all()
    page = request.GET.get('page',1)
    
    try:
        paginator = Paginator(mensajes, 4)
        mensajes = paginator.page(page)
    except:
        raise Http404
    
    
    data = {
        'mensajes' : mensajes,
        'paginator' : paginator
    }
    
    return render(request, 'contacto/listar.html', data)

""""
Galeria

"""

def galeria(request):
    return render(request, 'tienda/galeria.html')

""""
Registro

"""

def registro(request):
    data = {
        'form' : CustomUserCreationForm
    }
    
    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data['username'], password=formulario.cleaned_data['password1'])
            login(request, user)
            messages.success(request, 'Te has Registrado Correctamente')
            #redirigir al home
            return redirect(to='home')
        data['form'] = formulario
            
    return render(request, 'registration/registro.html', data)


""""
Vistas Productos

"""
@permission_required('tienda.add_prodcto')
def agregar_producto(request):
    data = {
        'form' : ProductoForm()
    }
    
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Producto Agregado Correcatmente")
        else:
            data['form'] = formulario
    return render(request, 'producto/agregar.html', data)

@permission_required('tienda.view_prodcto')
def listar_productos(request):
    productos = Prodcto.objects.all()
    page = request.GET.get('page',1)
    
    try:
        paginator = Paginator(productos, 4)
        productos = paginator.page(page)
    except:
        raise Http404
    
    
    data = {
        'productos' : productos,
        'paginator' : paginator
    }
    
    return render(request, 'producto/listar.html', data)

@permission_required('tienda.change_prodcto')
def modificar_producto(request, id):
    
    producto = get_object_or_404(Prodcto, id=id)
    
    data = {
        'form': ProductoForm(instance=producto)
    }
    
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Editado Correcatmente")
            return redirect(to="listar_productos")
        data["form"] = formulario
        
    return render(request, 'producto/modificar.html', data)

@permission_required('tienda.delete_prodcto')
def eliminar_producto(request, id):
    producto = get_object_or_404(Prodcto, id=id)
    producto.delete()
    messages.success(request, "Eliminado Correcatmente")
    return redirect(to="listar_productos")

def detalle_producto(request, id):
    producto = get_object_or_404(Prodcto, id=id)
    #print(producto.precio)
    return render(request, 'producto/detalle.html', {'producto': producto})

""""
Vistas Marcas

"""
@permission_required('tienda.add_marca')
def agregar_marca(request):
    data = {
        'form' : MarcaForm()
    }
    
    if request.method == 'POST':
        formulario = MarcaForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Marca Agregada Correcatmente")
        else:
            data['form'] = formulario
    return render(request, 'marca/agregar.html', data)

@permission_required('tienda.view_marca')
def listar_marcas(request):
    marcas = Marca.objects.all()
    page = request.GET.get('page',1)
    
    try:
        paginator = Paginator(marcas, 4)
        marcas = paginator.page(page)
    except:
        raise Http404
    
    
    data = {
        'marcas' : marcas,
        'paginator' : paginator
    }
    
    return render(request, 'marca/listar.html', data)

@permission_required('tienda.change_prodcto')
def modificar_marca(request, id):
    
    marca = get_object_or_404(Marca, id=id)
    
    data = {
        'form': MarcaForm(instance=marca)
    }
    
    if request.method == 'POST':
        formulario = MarcaForm(data=request.POST, instance=marca)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Editado Correcatmente")
            return redirect(to="listar_marcas")
        data["form"] = formulario
        
    return render(request, 'marca/modificar.html', data)

@permission_required('tienda.delete_prodcto')
def eliminar_marca(request, id):
    marca = get_object_or_404(Marca, id=id)
    marca.delete()
    messages.success(request, "Eliminado Correcatmente")
    return redirect(to="listar_marcas")


""""
Vistas Perfil

"""

from django.views.generic.edit import UpdateView
from django.utils.decorators import method_decorator

@method_decorator(login_required, name='dispatch')
class ProfileUpdate(UpdateView):
    form_class = ProfileForm
    success_url = reverse_lazy('profile')
    
    def get_object(self):
        try:
            return Profile.objects.get(user=self.request.user)
        except Profile.DoesNotExist:
            return Profile.objects.create(user=self.request.user)
    
    
""""
Vistas Sobre mi

"""

def sobremi(request):
    return render(request, 'tienda/sobremi.html')

tienda/templates/tienda/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'tienda/img/globaltech.png' %}" type="image/x-icon">
    <title>Global Tech</title>
    <link
        href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,700;1,400;1,700&family=Open+Sans:ital,wght@0,400;0,700;1,600&display=swap"
        rel="stylesheet">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% block css %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'tienda/css/estilos.css' %}">

</head>

<body>


    <header id="header">

        <img class="menu" src="{% static 'tienda/img/menuiconwhite.png' %}" alt="menu" id="menu">
        <div class="contenedor_logo">
            <a href="{% url 'home' %}">
                <div class="navcelu">
                    <img class="logo" src="{% static 'tienda/img/globaltech.png' %}" alt="logo">
                    {% if user.is_authenticated %}
                    <div class="usuariocelu">
                        <a class="nombreusuario href="#"><b>{{ user.username }}</b></a>
                        {% if request.user.profile.avatar %}
                            <img src="{{request.user.profile.avatar.url}}" alt="user" width="30" height="30">
                        {% else %}
                            <img src="{% static 'registration/img/no-avatar.png' %}" alt="user" width="30" height="30">
                        {% endif %}
                    </div>
                    {% endif %}
                </div>
            </a>
        </div>

            <nav id="nav">
                <ul>
                    <li>
                        <a href="{% url 'home' %}">Inicio</a>
                    </li>
                    <li>
                        <a href="{% url 'contacto' %}">Contacto</a>
                    </li>
                    <li>
                        <a href="{% url 'galeria' %}">Galería</a>
                    </li>
                    <li>
                        <a href="{% url 'sobremi' %}">Sobre Mi</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}">Cerrar Sesión</a>
                        </li>
                        <li>
                            <a href="{% url 'profile' %}">Perfil</a>
                        </li>
                        {% load static %}
                            
                        <li class="liusuario">
                            <a class="nombreusuario href="#"><b>{{ user.username }}</b></a>
                            {% if request.user.profile.avatar %}
                                <img src="{{request.user.profile.avatar.url}}" alt="user" width="30" height="30">
                            {% else %}
                                <img src="{% static 'registration/img/no-avatar.png' %}" alt="user" width="30" height="30">
                            {% endif %}
                        </li>
                    
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Iniciar Sesión</a>
                        </li>
                        <li>
                            <a href="{% url 'registro' %}">Registrarte</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>

    </header>

    {% if user.is_authenticated %}
    <div class="barratareas">
        {% if perms.tienda.add_prodcto %}
        <li>
            <a href="{% url 'agregar_producto' %}">Agregar Producto</a>
        </li>
        {% endif %}
        {% if perms.tienda.add_marca %}
        <li>
            <a href="{% url 'agregar_marca' %}">Agregar Marca</a>
        </li>
        {% endif %}
        {% if perms.tienda.view_prodcto %}
        <li>
            <a href="{% url 'listar_productos' %}">Listado Productos</a>
        </li>
        {% endif %}
        {% if perms.tienda.view_marca %}
        <li>
            <a href="{% url 'listar_marcas' %}">Listado Marcas</a>
        </li>
        {% endif %}
        {% if perms.tienda.view_contacto %}
        <li>
            <a href="{% url 'listar_contactos' %}">Listado Mensajes</a>
        </li>
        {% endif %}
    </div>
    {% endif %}

    

    <div id="contenido">
        <h1 class="text-center text-white mt-5 mb-5">Global Tech</h1>
        {% block contenido %}
        {% endblock %}

    </div>

    <footer>
        <div class="marcas">
            <img src="{% static 'tienda/img/footer/apple.png' %}" alt="apple">
            <img src="{% static 'tienda/img/footer/lenovo.png' %}" alt="lenovo">
            <img src="{% static 'tienda/img/footer/microsoft.png' %}" alt="microsoft">
            <img src="{% static 'tienda/img/footer/samsung.png' %}" alt="samsung">
            <img src="{% static 'tienda/img/footer/xiaomi.png' %}" alt="xiaomi">
        </div>
        <div class="logo_footer">
            <a href="{% url 'home' %}">
                <img class="logo" src="{% static 'tienda/img/globaltech.png' %}" alt="logo">
            </a>
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <script src="{% static 'tienda/js/menu.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}
        {% for m in messages %}
            <script>
                Swal.fire({
                    "title": "Felicitaciones",
                    "text" : "{{m}}",
                    "icon" : "success"
                })
            </script>
        {% endfor %}
    {% endif %}
    

    {% block js %}

    {% endblock %}


</body>

</html>

tienda/templates/tienda/contacto.html
{% extends 'tienda/base.html' %}


{% block contenido %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card mt-4">
            <div class="card-body">
                <h2>Contactanos!</h2>
                <hr>
                <form action="" class="" method="POST">
                    {% csrf_token %}
                    {{ form | crispy }}
                    
                    <br>
                    <br>
                    <hr>
                    <div class="d-flex justify-content-end">
                        <button  type="reset" value="Cancelar" class="btn btn-secondary">
                            <a class="botonCancelar" href="{% url 'home' %}">
                                Cancelar
                            </a></button>
                    &nbsp;
                    <button class="btn btn-primary" type="submit" id="btnEnviar" class="button">Enviar</button>
                    </div>
                    {{mensaje}}
                
                </form>
            </div>
        </div>
    </div>
</div>

<div class="irinicio">
    <button  type="reset" value="Inicio" class="btn btn-secondary mb-3">
        <a class="botonCancelar" href="{% url 'home' %}">
            Inicio
        </a>
    </button>
</div>
{% endblock %}
    

tienda/templates/tienda/galeria.html
{% extends 'tienda/base.html' %}

{% load static %}


{% block js %}
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
{% endblock %}
    

{% block contenido %}

<h2 class="text-center text-white mt-5">Galería de nuestra tienda</h2>
<br><br>
<div class="galeria">
    <a data-fancybox="gallery" href="{% static 'tienda/img/tienda/tienda1.jpg' %}"><img src="{% static 'tienda/img/tienda/tienda1.jpg' %}"></a>
    <a data-fancybox="gallery" href="{% static 'tienda/img/tienda/tienda2.jpeg' %}"><img src="{% static 'tienda/img/tienda/tienda2.jpeg' %}"></a>
    <a data-fancybox="gallery" href="{% static 'tienda/img/tienda/tienda3.jpg' %}"><img src="{% static 'tienda/img/tienda/tienda3.jpg' %}"></a>
    <a data-fancybox="gallery" href="{% static 'tienda/img/tienda/tienda4.jpg' %}"><img src="{% static 'tienda/img/tienda/tienda4.jpg' %}"></a>
    <a data-fancybox="gallery" href="{% static 'tienda/img/tienda/tienda5.jpg' %}"><img src="{% static 'tienda/img/tienda/tienda5.jpg' %}"></a>
</div>
<div class="irinicio">
    <button  type="reset" value="Inicio" class="btn btn-secondary">
        <a class="botonCancelar" href="{% url 'home' %}">
            Inicio
        </a>
    </button>
</div>

{% endblock %}

tienda/templates/tienda/home.html
{% extends 'tienda/base.html' %}

{% load static %}

{% block js %}
<script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
<script>
    $(document).ready(function () {
        $('.slider').bxSlider({
            mode: 'fade',//horizontal, vertical, fade
            auto: true,
            pause: 2000
        });
    });
</script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
{% endblock %}

{% block contenido %}

<div class="row">
    <div class="col-8">
        <div class="slider">
            <div>
                <img src="{% static 'tienda/img/banner/banner1.png' %}" alt="">
            </div>
            <div>
                <img src="{% static 'tienda/img/banner/banner2.png' %}" alt="">
            </div>
            <div>
                <img src="{% static 'tienda/img/banner/banner3.png' %}" alt="">
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="carritonav">
            {% include 'carrito.html' %}
        </div>
    </div>
</div>




{% load humanize %}


    
    
    <div class="col-12">
        <div class="barrabusqueda mt-5 mb-5">
            <form class="" action="" method="GET">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Buscar" name="buscar" >
                    <button class="btn colorboton" type="submit" >Buscar</button>
                </div>
    
            </form>
        </div>
        <div class="productos">
            {% for d in data %}
            
            <div class="producto card m-2">
                <div class="contenedor_producto card-body">
                    {% if d.imagen %}
                    <img class="img-fluid" src="{{ d.imagen.url}}" alt="imagen producto">
                    {% endif %}
                    <div class="detalle">
                        <h5>{{d.marca | capfirst}}</h5>
                        <h2>{{d.nombre | title}}</h2>
                        <h3>{{d.precio | intcomma}} USD</h3>
                    </div>
                    <div>
                        <div style="display: flex; justify-content: center;">
                            <a class="btn colorboton" href="{% url 'detalle_producto' d.id %}">Detalle</a>
                        </div>
                        
                        <a href="{% url 'agregar' d.id %}" class="btn colorboton mt-2" >Agregar al Carrito</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    

<br><br>



{% endblock %}

tienda/templates/tienda/profile_form.html
{% extends 'tienda/base.html' %}

{% load static %}

{% block js %}
<script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
<script>
    $(document).ready(function () {
        $('.slider').bxSlider({
            mode: 'fade',//horizontal, vertical, fade
            auto: true,
            pause: 2000
        });
    });
</script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
{% endblock %}

{% block contenido %}
{% load crispy_forms_tags %}

<style>
    .errorlist {
        color: red;
    }

    label {
        display: none
    }
</style>
<main role="main">
    <div class="container text-white">
        <div class="row mt-3">
            <div class="col-md-9 mx-auto mb-5">
                <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                    <div class="row">
                        <!-- Previa del avatar -->
                        <div class="col-md-2  fotoperfil">
                            {% if request.user.profile.avatar %}
                            <img src="{{request.user.profile.avatar.url}}" class="img-fluid">
                            {% else %}
                            <img src="{% static 'registration/img/no-avatar.png' %}" class="img-fluid">
                            {% endif %}
                        </div>
                        <!-- Formulario -->
                        <div class="col-md-10">
                            <h3 class="perfil">Perfil</h3>
                            <input type="file" name="avatar" class="form-control-file mt-3" id="id_avatar">
                            {{ form.bio }}
                            {{ form.link }}
                            <input type="submit" class="btn btn-primary btn-block mt-3" value="Actualizar">
                            <a class="btn btn-primary btn-block mt-3" href="{% url 'home' %}">Inicio</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

tienda/templates/tienda/sobremi.html
{% extends 'tienda/base.html' %}

{% load static %}


{% block js %}
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
{% endblock %}
    

{% block contenido %}

<main role="main">
    <div class="container text-white">
        <div class="row mt-3">
            <div class="col-md-9 mx-auto mb-5">
                    <div class="row">
                        <!-- Previa del avatar -->
                        <div class="col-md-2 fotoperfil">
                            <img src="{% static 'sobremi/sobremi.jpg' %}" class="img-fluid">
                        </div>
                        <!-- Formulario -->
                        <div class="col-md-10">
                            <div class="fotoperfil">
                                <h2>Martin Tamola</h2>
                                <h3>Desarrollador Frontend | Backend</h3>
                                <p>Página desarrollada con Django. Para el curso de Python de Coder House</p>
                            </div>
                            <div style="display: flex; justify-content: center; margin-top: 50px;">
                                <a class="btn btn-primary btn-block mt-3" href="{% url 'home' %}">Inicio</a>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}